version: '3.3'

services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    ports:
      - "8020:8090"
    restart: unless-stopped
    volumes:
      - /srv/dim-server/appdata/beszel:/beszel_data
