version: '3.3'
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /mnt/HDD_8TB/server/apps/kavita/config:/config
      - /mnt/HDD_8TB/server/data/media/books:/data 
    ports:
      - 5000:5000
    restart: unless-stopped
