version: "3.3"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    env_file:
      - ../stack.env
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "3010:3000"
    volumes:
      - '${APPDATA}/homepage:/app/config'
      # Optional: allow Homepage to read running containers for widgets
      - /var/run/docker.sock:/var/run/docker.sock:ro
