version: '3.3'
services:
  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:latest'
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /srv/dim-server/appdata/prowlarr:/config
    ports:
      - '9696:9696'
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://prowlarr.home:9696
      - homepage.description=Indexer manager
