version: '3.3'
services:
  prowlarr:
    env_file:
    - ../stack.env
    image: 'lscr.io/linuxserver/prowlarr:latest'
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - '${APPDATA}/prowlarr:/config'
    ports:
      - '9696:9696'
    restart: unless-stopped
