version: '3.3'
services:
  prowlarr:
    env_file:
    - ../stack.env
    image: 'lscr.io/linuxserver/prowlarr:latest'
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /srv/dim-server/appdata/prowlarr:/config
    ports:
      - '9696:9696'
    restart: unless-stopped
