version: '3.3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true       # Remove old images after updating
      - WATCHTOWER_SCHEDULE=0 0 5 * * * # Run updates daily at 5 AM
      - WATCHTOWER_INCLUDE_STOPPED=true # Update stopped containers as well
      - WATCHTOWER_REVIVE_STOPPED=true  # Restart stopped containers after updating
      #- WATCHTOWER_LABEL_ENABLE=true  # Only update containers with the right label
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
