version: '3.3'
services:
  jellyfin:
    image: 'lscr.io/linuxserver/jellyfin:latest'
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - JELLYFIN_PublishedServerUrl=192.168.0.5
    volumes:
      - '/srv/dim-server/appdata/jellyfin:/config'
      - '/mnt/HDD_8TB/server/data/media/shows:/data/tvshows'
      - '/mnt/HDD_8TB/server/data/media/movies:/data/movies'
    ports:
      - '8920:8920'
      - '7359:7359/udp'
      - '1900:1900/udp'
    networks:
      - traefik-private
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.wouldyoukindly.enter`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    restart: unless-stopped

networks:
  traefik-private:
    external: true
