version: "3.3"

services:
  calibre:
    image: linuxserver/calibre:8.6.0
    container_name: calibre
    environment:
      - PUID=1000   # your user ID
      - PGID=1000   # your group ID
      - TZ=Europe/Zurich
      #- PASSWORD= #optional
      #- CLI_ARGS= #optional
    volumes:
      - /srv/dim-server/appdata/calibre:/config
      - /mnt/HDD_8TB/server/data/media/books:/books
      - /mnt/HDD_8TB/server/data/media/book_imports:/imports
      - /mnt/HDD_8TB/server/data/media/books_kepubified:/kepubified
    ports:
      - 5900:5900  # VNC port to access GUI
    networks:
      - traefik-private
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`calibre.wouldyoukindly.enter`)"
      - "traefik.http.routers.calibre.entrypoints=web"
      - "traefik.http.services.calibre.loadbalancer.server.port=8080"
    restart: unless-stopped

networks:
  traefik-private:
    external: true
