version: "3.3"

services:
  calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000   # your user ID
      - PGID=1000   # your group ID
      - TZ=Europe/Zurich
      #- PASSWORD= #optional
      #- CLI_ARGS= #optional
    volumes:
      - /mnt/HDD_8TB/server/configs/calibre:/config
      - /mnt/HDD_8TB/server/data/media/books:/books
      - /mnt/HDD_8TB/server/data/media/book_imports:/imports
      - /mnt/HDD_8TB/server/data/media/books_kepubified:/kepubified
    ports:
      - 8020:8080  # optional: calibre content-server web port
      - 5900:5900  # VNC port to access GUI
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /mnt/HDD_8TB/server/configs/calibre-web:/config
      - /mnt/HDD_8TB/server/data/media/books:/books  # SAME library as Calibre
    ports:
      - 8083:8083
    restart: unless-stopped
