version: '3.3'
services:
  qbittorrent:
    image: 'lscr.io/linuxserver/qbittorrent:latest'
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - WEBUI_PORT=8090
    volumes:
      - '/srv/dim-server/appdata/qbitorrent:/config'
      - '/srv/dim-server/downloads/incomplete:/incomplete'
      - '/mnt/HDD_8TB/server/data/torrents/complete:/downloads'
    ports:
      - '8090:8090'
      - '6881:6881'
      - '6881:6881/udp'
    restart: unless-stopped
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart qbittorrent; done"]
    restart: unless-stopped
