version: '3.3'
services:
  bazarr:
    image: 'lscr.io/linuxserver/bazarr:latest'
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - '/mnt/HDD_8TB/server/configs/bazarr:/config'
      - '/mnt/HDD_8TB/server/data/media/shows:/tv'
      - '/mnt/HDD_8TB/server/data/media/movies:/movies'
    ports:
      - '6767:6767'
    restart: unless-stopped
