version: '3.3'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    volumes:
      - /srv/dim-server/appdata/audiobookshelf:/config
      - /srv/dim-server/appdata/audiobookshelf/metadata:/metadata
      - /mnt/HDD_8TB/server/data/media/audiobooks:/audiobooks
      - /mnt/HDD_8TB/server/data/media/podcasts:/podcasts
    environment:
      - TZ=Europe/Zurich
